GET http://127.0.0.1:8000/colors

###
GET http://127.0.0.1:8000/stars

###
GET http://127.0.0.1:8000/planets

###
GET http://127.0.0.1:8000/planets2

###

POST http://127.0.0.1:8000/colors
Content-Type: application/json

{ "name": "purple", "hex_code" : "FF00FF" }
